### ISSUE TITLE
semantic-release support?

### ISSUE THREAD

**Issue by sergey-lapin** [lapanoid/redux-import-export-monitor#3] opened 2016-01-04 14:15 UTC
I want to integrate [semantic-release](https://github.com/semantic-release/semantic-release) and [commitizen](https://github.com/commitizen/cz-cli) with this project.
@calesce what do you think?

**Comment by calesce** [comment] 2016-01-05 08:58
Sure! I've never seen commitizen before, looks interesting. My commit messages leave much to be desired 😄

**Comment by sergey-lapin** [comment] 2016-01-11 10:23
I introduced https://github.com/leonardoanalista/cz-customizable check out .cz-config.js file, you may define your own scopes or overrides there.

**Comment by sergey-lapin** [comment] 2016-01-11 10:28
I also added some helper scripts `npm run cz` & `npm run czp`, I just get used to them)

**Comment by sergey-lapin** [comment] 2016-01-11 10:52
@calesce could you give me rights to https://www.npmjs.com/package/redux-import-export-monitor, as I can't setup semantic-release require push to npm https://travis-ci.org/lapanoid/redux-import-export-monitor/builds/101554975

**Comment by calesce** [comment] 2016-02-09 16:09
whoops. I forgot about this, just added you :smile_cat:

**Comment by calesce** [comment] 2016-04-03 16:41
Just cut a release using the commitizen/semantic-release workflow, so I'd say it's fair to close this!

**Closed as completed by calesce** 2016-04-03 16:41 UTC

**Comment by calesce** [comment] 2016-04-03 20:03
@lapanoid hmmm, semantic-release isn't letting me release from 6727155642b3bbfe2d7faf6139090e5ae8ff9abe, where I added `shouldComponentUpdate` and categorized it as a "perf" commit (via commitizen). Before I open an issue with semantic-release, do you know what the problem is?

Here's the error message:
<img width="419" alt="screen shot 2016-04-03 at 2 59 58 pm" src="https://cloud.githubusercontent.com/assets/5377524/14234610/cd20bb46-f9ac-11e5-8cab-417c9f55bfc5.png">

I went ahead and published 0.2.3 manually,

**Comment by sergey-lapin** [comment] 2016-04-03 20:15
Let me see...

**Comment by sergey-lapin** [comment] 2016-04-03 20:40
Here is an issue, that is still open that we depend on to fix this  https://github.com/semantic-release/commit-analyzer/issues/3 and it is still open.
Meanwhile you can only use 'fix' commit to trigger patch change and npm publish.
